server:
  port: 8082

spring:
  application:
    name: theater
  data:
    mongodb:
      port: 27018
      database: theaters
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://dev-7678651.okta.com/oauth2/default/v1/introspect
          client-secret: KK3iQb0p4zpFQPB5d5m4b7_NjBhVOY5y2sZeXMDH
          client-id: 0oa8adqy9WCK2Zn6L5d6
logging:
  level:
    root: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: DEBUG
    org.springframework.data: DEBUG
    org.springframework.boot: DEBUG
    com.okta: TRACE
    org.mongodb: INFO
    de.flapdoodle: INFO
    com.nimbusds: DEBUG




mongo-dump: /home/indiepopart/mongodb/theaters.bson
